env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - standard-with-typescript
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.eslint.json
rules: {}
